### ISSUE TITLE
Language and formatting tags are added to the headings

### ISSUE THREAD

**Issue by peter88213** [peter88213/yW2OO#2]
I tried yWOO. It works very well but language tags are added to some chapter titles and scene contents.

Header 1 titles show in bold, header 2 do not (novelyst shows the proper hierarchical structure).

[There is no Discussion tab on the yWOO  Github page]

![image](https://github.com/user-attachments/assets/5a6f0ad9-b762-49dd-8855-fee599d4f6fa)

_Originally posted by @JPhB in https://github.com/peter88213/nv_yw7/issues/1#issuecomment-2364799816_

**Comment by peter88213** [comment]
yW2OO considers all language settings of the original file, so they can be used for document export. 
Actually, the tags only take effect on the scene content. 

Actually, headings are not expected to be formatted in a proper-set up document. 
however, the converter should strip formattings, if any. 
Since I use the yw7 format no longer myself, I cannot promise to fix this. I will open an issue in the PyWriter anyway. 

For now, you can make sure that the headings are not hard-formatted in your original document. With LibreOffice, select the headings (you can use the Find dialog with "Format" activated), and reset the formatting with `Ctrl`-`M`.
Then you can remove language tags: Select the whole document with `Ctrl´-`A`, then set the language to your default language. I hope this works for you.

**Comment by peter88213** [comment]
> Header 1 titles show in bold, header 2 do not (novelyst shows the proper hierarchical structure).

Be aware, yWriter doesnt display a structure tree. Using boldface is the only way to show the higher hierarchy level in the chapter list. In yWriter, the meaning is "This chapter begins a new section". Usually, this is an empty chapter, just to generate a "Part" heading. 
In contrast to *novelyst*, *novelibre* also sets parts and chapters on the same tree level to make it easier to move the part boundaries (see documentation).

**Comment by peter88213** [comment]
Version 5.7.7 removes language and formatting tags from the headings when importing a work-in-progress.

**Comment by JPhB** [comment]
Thanks for the fix (I merely convert the rtf file to odt online and never use OO).

Language tag remains in the Contents however.

So every header is a chapter. One would think that header 2s would become scenes in the header 1 chapter they are under..

**Comment by peter88213** [comment]
> Language tag remains in the Contents however.

This is intended, so the language information wouldn't get lost in case you re-export your manuscript with yW2OO. See the [documentation about language handling](https://peter88213.github.io/yW2OO/help/import_menu#about-document-language-handling). The language tags are made in a way that doesn't interfere with yWriter's native document export.
It is the user's responsibility to set up the language information in the initial document, isn't it?

> One would think that header 2s would become scenes in the header 1 chapter they are under.

Only those who haven't read the [documentation about setting up an outline](https://peter88213.github.io/yW2OO/help/import_menu#how-to-set-up-an-outline-for-export). 
If this isn't clear enough, you might want to read the chapter about document structure in the [novelibre manual](https://peter88213.github.io/nvhelp-en/basic_concepts.html#the-book-hierarchy). This basically applies to *novelyst*, too.

**Comment by JPhB** [comment]
> Only those who haven't read the documentation about setting up a document for import.

Yes, sorry. 

I did put *** between scenes titles now, but they all come up in the Chapter content, rather than scenes.

![image](https://github.com/user-attachments/assets/9384b614-822c-4b5b-b465-5028b800123e)

**Comment by peter88213** [comment]
You have to put blanks between the asterisks.

**Comment by JPhB** [comment]
Sorry for not reading more carefully once again.

It works nicely now. Thanks

**Comment by peter88213** [comment]
Fine, so all special characters are now transferred to yWriter? 
May I ask which word processor you used for writing your initial manuscript, and how you converted it to ODT?

**Comment by JPhB** [comment]
Well, scene titles aren't there, it's just Scene 1, Scene 2, etc. Before commenting I was waiting to look at the doc later in case I missed something :)

I use old Word 2003 and Atlantis Word Processor, largely because of the vertical screen split

I convert to odt using one of the many online converters, such as https://cloudconvert.com/rtf-to-odt.

**Comment by peter88213** [comment]
If you still have novelyst, there is an easy way to remove the language tags. 
In the downloaded zip file of the novelyst release, there is an **add-on** subdirectory with extra plugins. 
You can copy the **novelyst_ywriter.py** file into the **plugin** directory of your novelyst installation 
`C:\Users\<username>\.pywriter\novelyst\plugin`
This should add a *Remove non-yWriter data* entry to the *File* menu. After starting this, just close novelyst without saving.

**Comment by peter88213** [comment]
Just on a side note, the _Atlantis_ word processor looks nice with the split screen. Anyway, _LibreOffice_ can open several windows for the same document.

**Comment by JPhB** [comment]
Thanks for the notes.

I still don't get scene titles. The line after * * * is ignored. The rest goes into content, as expected.

The doc says "Comments right at the scene beginning are considered scene titles". Does the word "comment" refer to an actual OO Comment?

**Comment by peter88213** [comment]
> The doc says "Comments right at the scene beginning are considered scene titles". Does the word "comment" refer to an actual OO Comment?

Yes, this is how it looks like: 

![Working example](https://github.com/peter88213/yW2OO/blob/main/docs/Screenshots/work-in-progress01.png?raw=true)

**Comment by JPhB** [comment]
That's very clear now. OO/LO is really needed then.

**Comment by peter88213** [comment]
You can create comments with Word, and then convert from DOCX to ODT. This works with LibreOffice. 
However, it may be easier to enter the scene titles in yWriter. Scene titles in manuscripts are unusual, I think.

If I had a manuscript A with scene titles as 3rd level headings, I guess I would make a copy B without the scene 
titles but scene dividers and import it as work-in progress to the new yWriter project B. 
Then I would delete the body text from document A, make sure there are no scene dividers, and create yWriter project A from the outline. 
After checking whether the yWriter projects A and B have the same chapter and scene structure,  I would export a manuscript from project B, rename it after A and reimport this to yWriter project A, thus adding the scene contents. 
Then project B can be discarded, and A should contain scene titles and content. 
This works only, if there is a 3rd level heading for each scene in document A, and the scene dividers are properly set in document B.
